- Fix section reading for certain shells - Fix iniempty.test
git-svn-id: svn+ssh://svn.xp-framework.net/home/svn/xpadmin/trunk/releases/bin@222 4ada86be-2990-db11-8b6f-0050450081cd

diff --git a/unix/src/exec.in b/unix/src/exec.in
--- a/unix/src/exec.in
+++ b/unix/src/exec.in
@@ -9,7 +9,7 @@ if [ "" = "$USE_XP" ] ; then
       ;;
 
       \[*\])
-        section=${line#[}
+        section=${line#\[}
         section=${section%]}
       ;;
 
@@ -24,6 +24,10 @@ if [ "" = "$USE_XP" ] ; then
   done < "$base"/xp.ini
 else
   USE_XP=$(translate_paths "." "$USE_XP")
+fi
+if [ "" = "$USE_XP" ] ; then
+  echo "*** Cannot determine use_xp setting" >&2
+  exit
 fi
 
 args="-dinclude_path=\".$PATHSEP$USE_XP$PATHSEP$PATHSEP$INCLUDE\"${ifs}-dmagic_quotes_gpc=0"
