- Show "Invalid argument ..." message on STDERR
git-svn-id: svn+ssh://svn.xp-framework.net/home/svn/xpadmin/trunk/releases/bin@219 4ada86be-2990-db11-8b6f-0050450081cd

diff --git a/unix/src/xp.in b/unix/src/xp.in
--- a/unix/src/xp.in
+++ b/unix/src/xp.in
@@ -29,7 +29,7 @@ for arg in "$@" ; do
       OPTIND=$(expr $OPTIND + 1)
       ;;
     -*)               # Any other arg
-      echo "*** Invalid argument $arg"
+      echo "*** Invalid argument $arg" >&2
       echo ${USAGE}
       exit
       ;;
