- Always check for web.ini existance except when "-?" is passed

diff --git a/unix/src/xpws.in b/unix/src/xpws.in
--- a/unix/src/xpws.in
+++ b/unix/src/xpws.in
@@ -39,6 +39,7 @@ while [ $# != 0 ]; do
     -?)
       RUNNER=class
       TOOL="xp.scriptlet.Usage|xpws.txt"
+      WEB_CONFIG=?
       break
       ;;
     *:*)
@@ -61,20 +62,20 @@ EXEC($RUNNER, $INCLUDE_PATH, $TOOL)
 
 #include <instance.in>
 
+if [ $WEB_CONFIG != "?" ] && [ ! -e "$WEB_CONFIG/web.ini" ] ; then
+  echo "*** Cannot find the web configuration web.ini in $WEB_CONFIG/, exiting." >&2
+  exit 3
+fi
+
 if [ $RUNNER = class ] ; then
   ${XP_EXE}${ifs}${args}${ifs}$tool ${ARGS} "$@"
 else
-  if [ ! -e "$WEB_CONFIG/web.ini" ] ; then
-    echo "*** Cannot find the web configuration web.ini in $WEB_CONFIG/, exiting." >&2
-    exit 3
-  fi
-
   export SERVER_PROFILE
   export DOCUMENT_ROOT
   export WEB_ROOT
   ${XP_EXE}${ifs}-S${ifs}${ADDR}${ifs}${root}-duser_dir="$WEB_CONFIG"${ifs}${args}${ifs}$tool ${ARGS} "$@" &
   PID=$!
-  echo "[xpws-$SERVER_PROFILE#$PID] running $ADDR @ $WEB_ROOT. Press <Enter> to exit"
+  echo "[xpws-$SERVER_PROFILE#$PID] running $ADDR @ $WEB_ROOT - Press <Enter> to exit"
   read enter
   echo "[xpws-$SERVER_PROFILE#$PID] shutting down..."
   kill -TERM $PID
