- Check for etc/web.ini and refuse to start

diff --git a/unix/src/xpws.in b/unix/src/xpws.in
--- a/unix/src/xpws.in
+++ b/unix/src/xpws.in
@@ -1,5 +1,10 @@
 #include <common.in>
 
+if [ ! -e "etc/web.ini" ] ; then
+  echo "*** Cannot find the web configuration web.ini in etc/, exiting." >&2
+  exit 3
+fi
+
 EXEC("web", ".", "")
 
 SERVER_PROFILE=dev
