- Implement "-c", "-w" and "-cp" options for Un*x

diff --git a/unix/src/xpws.in b/unix/src/xpws.in
--- a/unix/src/xpws.in
+++ b/unix/src/xpws.in
@@ -2,7 +2,11 @@
 
 RUNNER=web
 TOOL=
+INCLUDE_PATH="."
 SERVER_PROFILE=dev
+WEB_ROOT=.
+WEB_CONFIG=etc
+root=
 
 while [ $# != 0 ]; do
   case $1 in
@@ -15,10 +19,22 @@ while [ $# != 0 ]; do
       root="-t|$2|"
       shift 2
       ;;
+    -c)
+      WEB_CONFIG=$2
+      shift 2
+      ;;
+    -w)
+      WEB_ROOT=$2
+      shift 2
+      ;;
+    -cp)
+      INCLUDE_PATH=${INCLUDE_PATH}${PATHSEP}$2
+      shift 2
+      ;;
     -i)
       RUNNER=class
-      TOOL="xp.scriptlet.Inspect|.|${SERVER_PROFILE}|${server-localhost}:${port-8080}"
-      break
+      TOOL='xp.scriptlet.Inspect|${WEB_ROOT}|${WEB_CONFIG}|${SERVER_PROFILE}|${ADDR}'
+      shift 1
       ;;
     -?)
       RUNNER=class
@@ -40,23 +56,25 @@ while [ $# != 0 ]; do
 done
 
 ADDR=${server-localhost}:${port-8080}
-EXEC($RUNNER, ".", $TOOL)
+eval 'TOOL="'$TOOL'"'
+EXEC($RUNNER, $INCLUDE_PATH, $TOOL)
 
 #include <instance.in>
 
 if [ $RUNNER = class ] ; then
   ${XP_EXE}${ifs}${args}${ifs}$tool ${ARGS} "$@"
 else
-  if [ ! -e "etc/web.ini" ] ; then
-    echo "*** Cannot find the web configuration web.ini in etc/, exiting." >&2
+  if [ ! -e "$WEB_CONFIG/web.ini" ] ; then
+    echo "*** Cannot find the web configuration web.ini in $WEB_CONFIG/, exiting." >&2
     exit 3
   fi
 
   export SERVER_PROFILE
   export DOCUMENT_ROOT
-  ${XP_EXE}${ifs}-S${ifs}${ADDR}${ifs}${root}${args}${ifs}$tool ${ARGS} "$@" &
+  export WEB_ROOT
+  ${XP_EXE}${ifs}-S${ifs}${ADDR}${ifs}${root}-duser_dir="$WEB_CONFIG"${ifs}${args}${ifs}$tool ${ARGS} "$@" &
   PID=$!
-  echo "[xpws-$SERVER_PROFILE#$PID] running $ADDR. Press <Enter> to exit"
+  echo "[xpws-$SERVER_PROFILE#$PID] running $ADDR @ $WEB_ROOT. Press <Enter> to exit"
   read enter
   echo "[xpws-$SERVER_PROFILE#$PID] shutting down..."
   kill -TERM $PID
