- Check for etc/web.ini after parsing parameters, usage now works   regardless of directory xpws is executed in

diff --git a/unix/src/xpws.in b/unix/src/xpws.in
--- a/unix/src/xpws.in
+++ b/unix/src/xpws.in
@@ -1,10 +1,5 @@
 #include <common.in>
 
-if [ ! -e "etc/web.ini" ] ; then
-  echo "*** Cannot find the web configuration web.ini in etc/, exiting." >&2
-  exit 3
-fi
-
 RUNNER=web
 TOOL=
 SERVER_PROFILE=dev
@@ -47,6 +42,11 @@ EXEC($RUNNER, ".", $TOOL)
 if [ $RUNNER = class ] ; then
   ${XP_EXE}${ifs}${args}${ifs}$tool ${ARGS} "$@"
 else
+  if [ ! -e "etc/web.ini" ] ; then
+    echo "*** Cannot find the web configuration web.ini in etc/, exiting." >&2
+    exit 3
+  fi
+
   export SERVER_PROFILE
   export DOCUMENT_ROOT
   ${XP_EXE}${ifs}-S${ifs}${ADDR}${ifs}${root}${args}${ifs}$tool ${ARGS} "$@" &
